sudo: true
language: java
jdk:
  - openjdk9 

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo cp -f -v ./settings.xml /usr/local/maven/conf
  
jobs:
  include:
    - stage: tests
      script: "mvn clean package"
      
