sudo: true
os: linux
dist: xenial
language: java
jdk:
  - openjdk8 

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo cp -f -v ./settings.xml /usr/local/maven/conf
  
install: skip
  
deploy:
  - skip_cleanup: true
  - provider: script
    script: mvn clean deploy -DskipTests -DmuleDeploy -Denv=$MULE_ENV -Dch.environment=$CH_ENVIRONMENT -Dch.username=$CH_USERNAME -Dch.password=$CH_PASSWORD -Denv.clientId=$ANYPOINT_CLIENT_ID -Denv.clientSecret=$ANYPOINT_CLIENT_SECRET -Dch.application.name=$CH_APP_NAME -Dch.businessGroupId=$BUSINESS_GROUP -Dch.workerType=$CH_WORKERTYPE -Dch.workers=$CH_WORKERS
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(master|release|develop)$ && $CONTINUOUS_DEPLOYMENT = "true"
   
